minecraft_version=1.21.11
fabric_loader_version=0.16.10
fabric_api_version=0.112.0+1.21.11
yarn_mappings=1.21.11+build.1
loom_version=1.8.1
java_version=21
org.gradle.jvmargs=-Djavax.net.ssl.trustStore=/usr/lib/jvm/java-21-openjdk-amd64/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit